---
output:
  ioslides_presentation:
    widescreen: true
    css: style.css
---

## Agency is Essential to God's Plan

"And the Lord said: Whom shall I send? And one answered like unto the Son of Man: Here am I, send me. And another answered and said: Here am I, send me. And the Lord said: I will send the first. And the second was angry, and kept not his first estate; and, at that day, many followed after him."

Abraham 3:27-28.

"It is important to recognize that Lucifer did not present his plan. He rebelled against his Father's plan."

David A. Bednar.

## Self-Centeredness Undermines our Spiritual Progression

"And I, the Lord God, spake unto Moses, saying: That Satan, whom thou hast commanded in the name of mine Only Begotten, is the same which was from the beginning, and he came before me, saying—Behold, here am I, send me, I will be thy son, and I will redeem all mankind, that one soul shall not be lost, and surely I will do it; wherefore give me thine honor."

Moses 4:1

## Why Have Agency?

The purpose of agency is not to do what we want. 

The purpose is to give us the **opportunity to choose God**, and to love and serve our brothers and sisters.

## The Gift of Agency

"We use the gift of choice, our precious agency, a gift whose value is next to life itself, to say to our Father: I am Yours."

Neil L. Anderson, "Settle This in Your Hearts", 15 Sep. 2026.